spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onlinemusic?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 120125hzy.


  servlet:
    multipart:
      location: /Java/Music
      max-file-size: 20MB
      max-request-size: 200MB
music:
  #path: /root/music/
  path: D:/Java/Music/
server:
  port: 8081
  #servlet:
    #context-path: /music