server:
  port: 80
  servlet:
    context-path: /covid

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/covid?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 120125hzy.
#mybatis:
 # mapper-locations: classpath:mybatis/**Mapper.xml
